# SITE CONFIGURATION
baseurl: /blog # the subpath of your site, e.g. /blog/
url: "https://carloselhalabi.github.io/blog" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Mi hermana estÃ¡ equivocada 
  avatar: avatar.jpg
  gravatar: # Email MD5 hash
  description: "A picture of myself for the future times." # used by search engines

  # Header and footer text
  header_text: >
      <p> To live is to suffer, to survive is to find meaning in the suffering. <br> &mdash; <strong>Friedrich Nietzsche</strong></p>
  header_text_feature_image: "img/nietzsche.jpg"
  footer_text: >
   Made with something people call 'love'. Powered by the magic of <a href="http://jekyllrb.com">Jekyll</a> with a modified version of <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  # Icons
  rss: true 
  email_address: "c@elhalabi.org" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "carloselhalabi"
  flickr:
  github: "carloselhalabi"
  google_plus:
  instagram: "carloselhalabi"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "carloselhalabi"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow my RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
google_fonts: "Source+Sans+Pro:400,700,700italic,400italic|Playfair+Display:400,700|PT+Sans:400,700,700italic,400italic"
  # Post navigation
post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
gems:
    - jekyll-compass
sass:
  sass_dir: _sass
  style: :compressed
